// Generated by ReScript, PLEASE EDIT WITH CARE

import * as State from "./State.res.mjs";
import * as Sidebar from "./Sidebar.res.mjs";
import * as TasksIndex from "./TasksIndex.res.mjs";
import * as Hooks from "preact/hooks";
import * as JsxRuntime from "preact/jsx-runtime";

function App(props) {
  var state = State.TasksFSM.stateSignal.value;
  Hooks.useEffect((function () {
          State.TasksFSM.dispatch("Fetch");
          State.ToasterFSM.dispatch({
                TAG: "Toast",
                _0: {
                  title: "Test",
                  message: "Test toast message",
                  duration: 0,
                  status: "Info"
                }
              });
        }), []);
  var tmp;
  tmp = typeof state !== "object" ? "Tasky" : (
      state.TAG === "Loading" ? JsxRuntime.jsx("div", {
              children: "Loading..."
            }) : JsxRuntime.jsx("main", {
              children: JsxRuntime.jsx(TasksIndex.make, {
                    tasks: state._0.tasks
                  }),
              className: "max-w-4xl flex-grow mx-auto px-4 py-20 overflow-auto"
            })
    );
  return JsxRuntime.jsxs("div", {
              children: [
                tmp,
                JsxRuntime.jsx(Sidebar.make, {})
              ],
              className: "flex flex-row items-stretch min-h-screen"
            });
}

var make = App;

export {
  make ,
}
/* State Not a pure module */
