// Generated by ReScript, PLEASE EDIT WITH CARE


var Signal = {};

var $$AbortController = {
  Signal: Signal
};

var FormEvent = {};

export {
  $$AbortController ,
  FormEvent ,
}
/* No side effect */
