// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Task from "./Task.res.mjs";
import * as Spice from "@greenlabs/ppx-spice/src/rescript/Spice.res.mjs";
import * as DateTime from "./DateTime.res.mjs";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Core__Promise from "@rescript/core/src/Core__Promise.res.mjs";
import * as Signals from "@preact/signals";

var Task$1 = {};

var NewTask = {};

var Tasks = {};

var Toast = {};

var App = {};

var Actions = {
  Task: Task$1,
  NewTask: NewTask,
  Tasks: Tasks,
  Toast: Toast,
  App: App
};

var actionSignal = Signals.signal("Init");

function rootDispatch(action) {
  actionSignal.value = action;
}

function dispatch(action) {
  actionSignal.value = {
    TAG: "OpenTask",
    _0: action
  };
}

function reduce(prevState, action) {
  if (typeof action !== "object" && action === "Init") {
    return prevState;
  }
  if (typeof prevState !== "object") {
    if (typeof action !== "object") {
      return prevState;
    }
    if (action.TAG !== "Open") {
      return prevState;
    }
    var taskId = action._0;
    var promise = Core__Promise.$$catch(Task.fetchTask(taskId).then(function (task) {
              actionSignal.value = {
                TAG: "OpenTask",
                _0: {
                  TAG: "Fetched",
                  _0: task
                }
              };
              return Promise.resolve(task);
            }), (function (error) {
            console.error(error);
            actionSignal.value = {
              TAG: "OpenTask",
              _0: {
                TAG: "Error",
                _0: error,
                _1: taskId
              }
            };
            return Promise.reject(error);
          }));
    return {
            TAG: "Fetching",
            _0: promise
          };
  } else {
    switch (prevState.TAG) {
      case "Fetching" :
          if (typeof action !== "object") {
            return prevState;
          }
          switch (action.TAG) {
            case "Fetched" :
                return {
                        TAG: "Active",
                        _0: action._0
                      };
            case "Error" :
                return {
                        TAG: "Error",
                        _0: action._0,
                        _1: action._1
                      };
            default:
              return prevState;
          }
      case "Active" :
          if (typeof action !== "object") {
            if (action === "ClockIn") {
              return {
                      TAG: "Running",
                      _0: prevState._0,
                      _1: {
                        id: "",
                        start_time: DateTime.now(),
                        end_time: undefined,
                        notes: "",
                        interrupted_by_task_id: undefined
                      }
                    };
            } else {
              return prevState;
            }
          } else if (action.TAG === "UpdateTask") {
            return {
                    TAG: "Active",
                    _0: action._0
                  };
          } else {
            return prevState;
          }
      case "Running" :
          var session = prevState._1;
          var task = prevState._0;
          if (typeof action === "object") {
            if (action.TAG === "UpdateTask") {
              return {
                      TAG: "Running",
                      _0: action._0,
                      _1: session
                    };
            } else {
              return prevState;
            }
          }
          switch (action) {
            case "ClockOut" :
                return {
                        TAG: "Active",
                        _0: {
                          id: task.id,
                          title: task.title,
                          notes: task.notes,
                          estimated_time: task.estimated_time,
                          estimated_time_map: task.estimated_time_map,
                          due_date: task.due_date,
                          completed_at: task.completed_at,
                          created_at: task.created_at,
                          updated_at: task.updated_at,
                          parent_task_id: task.parent_task_id,
                          tracked_time: task.tracked_time,
                          time_sessions: Belt_Array.concatMany([
                                task.time_sessions,
                                [{
                                    id: session.id,
                                    start_time: session.start_time,
                                    end_time: DateTime.now(),
                                    notes: session.notes,
                                    interrupted_by_task_id: session.interrupted_by_task_id
                                  }]
                              ])
                        }
                      };
            default:
              return prevState;
          }
      case "Error" :
          return prevState;
      
    }
  }
}

var TaskFSM = {
  dispatch: dispatch,
  reduce: reduce
};

function title(draft, title$1) {
  return {
          title: title$1,
          notes: draft.notes,
          estimated_time_map: draft.estimated_time_map,
          due_date: draft.due_date,
          parent_task_id: draft.parent_task_id
        };
}

function estimatedTimeHours(draft, hours) {
  var init = draft.estimated_time_map;
  return {
          title: draft.title,
          notes: draft.notes,
          estimated_time_map: {
            hours: hours,
            minutes: init.minutes
          },
          due_date: draft.due_date,
          parent_task_id: draft.parent_task_id
        };
}

function estimatedTimeMinutes(draft, minutes) {
  var init = draft.estimated_time_map;
  return {
          title: draft.title,
          notes: draft.notes,
          estimated_time_map: {
            hours: init.hours,
            minutes: minutes
          },
          due_date: draft.due_date,
          parent_task_id: draft.parent_task_id
        };
}

function dueDate(draft, due_date) {
  return {
          title: draft.title,
          notes: draft.notes,
          estimated_time_map: draft.estimated_time_map,
          due_date: due_date,
          parent_task_id: draft.parent_task_id
        };
}

function parentTask(draft, parent_task_id) {
  return {
          title: draft.title,
          notes: draft.notes,
          estimated_time_map: draft.estimated_time_map,
          due_date: draft.due_date,
          parent_task_id: parent_task_id
        };
}

function notes(draft, notes$1) {
  return {
          title: draft.title,
          notes: notes$1,
          estimated_time_map: draft.estimated_time_map,
          due_date: draft.due_date,
          parent_task_id: draft.parent_task_id
        };
}

var Reducers = {
  title: title,
  estimatedTimeHours: estimatedTimeHours,
  estimatedTimeMinutes: estimatedTimeMinutes,
  dueDate: dueDate,
  parentTask: parentTask,
  notes: notes
};

function dispatch$1(action) {
  actionSignal.value = {
    TAG: "NewTask",
    _0: action
  };
}

function reduce$1(prevState, action) {
  if (typeof action !== "object" && action === "Init") {
    return prevState;
  }
  if (typeof prevState !== "object") {
    if (typeof action !== "object" && action === "Create") {
      return {
              TAG: "Active",
              _0: {
                title: "",
                notes: "",
                estimated_time_map: {
                  hours: 0,
                  minutes: 20
                },
                due_date: undefined,
                parent_task_id: undefined
              }
            };
    } else {
      return prevState;
    }
  }
  if (prevState.TAG === "Active") {
    var draft = prevState._0;
    if (typeof action !== "object") {
      if (action === "Create") {
        return prevState;
      }
      var promise = Core__Promise.$$catch(Task.createTask(draft).then(function (task) {
                actionSignal.value = {
                  TAG: "NewTask",
                  _0: {
                    TAG: "Saved",
                    _0: task
                  }
                };
                return Promise.resolve(task);
              }), (function (error) {
              console.error(error);
              actionSignal.value = {
                TAG: "NewTask",
                _0: {
                  TAG: "Error",
                  _0: error,
                  _1: draft
                }
              };
              return Promise.reject(error);
            }));
      return {
              TAG: "Saving",
              _0: draft,
              _1: promise
            };
    } else {
      switch (action.TAG) {
        case "Update" :
            var field = action._0;
            var tmp;
            switch (field.TAG) {
              case "Title" :
                  tmp = title(draft, field._0);
                  break;
              case "EstimateHours" :
                  tmp = estimatedTimeHours(draft, field._0);
                  break;
              case "EstimateMinutes" :
                  tmp = estimatedTimeMinutes(draft, field._0);
                  break;
              case "Notes" :
                  tmp = notes(draft, field._0);
                  break;
              case "ParentTask" :
                  tmp = parentTask(draft, field._0);
                  break;
              case "DueDate" :
                  tmp = dueDate(draft, field._0);
                  break;
              
            }
            return {
                    TAG: "Active",
                    _0: tmp
                  };
        case "Saved" :
        case "Error" :
            return prevState;
        
      }
    }
  } else {
    var draft$1 = prevState._0;
    if (typeof action !== "object") {
      return prevState;
    }
    switch (action.TAG) {
      case "Saved" :
          return {
                  TAG: "Active",
                  _0: {
                    title: "",
                    notes: "",
                    estimated_time_map: draft$1.estimated_time_map,
                    due_date: draft$1.due_date,
                    parent_task_id: draft$1.parent_task_id
                  }
                };
      case "Error" :
          return {
                  TAG: "Active",
                  _0: action._1
                };
      default:
        return prevState;
    }
  }
}

var NewTaskFSM = {
  Reducers: Reducers,
  dispatch: dispatch$1,
  reduce: reduce$1
};

var actionSignal$1 = Signals.signal("Init");

function reduce$2(prevState, action) {
  if (typeof action === "object") {
    if (typeof prevState !== "object" || prevState.TAG !== "Loading") {
      return prevState;
    } else {
      return {
              TAG: "Tasks",
              _0: {
                tasks: action._0
              }
            };
    }
  }
  if (action === "Init") {
    return prevState;
  }
  var promise = Task.fetchAll();
  return {
          TAG: "Loading",
          _0: promise.then(function (tasks) {
                actionSignal$1.value = {
                  TAG: "Fetched",
                  _0: tasks
                };
                return Promise.resolve(tasks);
              })
        };
}

var stateSignal = Signals.signal("Empty");

var transitionSignal = Signals.signal({
      prev: "Empty",
      next: "Empty",
      action: "Init",
      created_at: DateTime.now()
    });

Signals.effect(function () {
      var action = actionSignal$1.value;
      var prevState = stateSignal.peek();
      var nextState = reduce$2(prevState, action);
      if (prevState !== nextState) {
        Signals.batch(function () {
              stateSignal.value = nextState;
              transitionSignal.value = {
                prev: prevState,
                next: nextState,
                action: action,
                created_at: DateTime.now()
              };
            });
      }
      
    });

function dispatch$2(action) {
  actionSignal$1.value = action;
}

function getTasks() {
  var state = stateSignal.value;
  if (typeof state !== "object") {
    return [];
  } else if (state.TAG === "Loading") {
    return [];
  } else {
    return state._0.tasks;
  }
}

var TasksFSM = {
  actionSignal: actionSignal$1,
  reduce: reduce$2,
  stateSignal: stateSignal,
  transitionSignal: transitionSignal,
  dispatch: dispatch$2,
  getTasks: getTasks
};

var actionSignal$2 = Signals.signal("None");

function reduce$3(prevState, action) {
  if (typeof prevState !== "object") {
    if (typeof action !== "object" || action.TAG !== "Toast") {
      return prevState;
    } else {
      return {
              TAG: "Active",
              _0: [{
                  toast: action._0,
                  state: "Toasting"
                }]
            };
    }
  }
  var msgs = prevState._0;
  if (typeof action !== "object") {
    return prevState;
  }
  switch (action.TAG) {
    case "Toast" :
        return {
                TAG: "Active",
                _0: Belt_Array.concatMany([
                      [{
                          toast: action._0,
                          state: "Toasting"
                        }],
                      msgs
                    ])
              };
    case "Update" :
        var toastAction = action._1;
        var targetIdx = action._0;
        var msgs$1 = msgs.map(function (msg, idx) {
              if (idx !== targetIdx) {
                return msg;
              }
              var tmp;
              tmp = toastAction === "Pop" ? "Popped" : "Dismissed";
              return {
                      toast: msg.toast,
                      state: tmp
                    };
            });
        return {
                TAG: "Active",
                _0: msgs$1
              };
    case "Remove" :
        var targetIdx$1 = action._0;
        var msgs$2 = msgs.filter(function (_m, idx) {
              return idx !== targetIdx$1;
            });
        if (msgs$2.length !== 0) {
          return {
                  TAG: "Active",
                  _0: msgs$2
                };
        } else {
          return "Ready";
        }
    
  }
}

var stateSignal$1 = Signals.signal("Ready");

var transitionSignal$1 = Signals.signal({
      prev: "Ready",
      next: "Ready",
      action: "None",
      created_at: DateTime.now()
    });

Signals.effect(function () {
      var action = actionSignal$2.value;
      var prevState = stateSignal$1.peek();
      var nextState = reduce$3(prevState, action);
      if (prevState !== nextState) {
        Signals.batch(function () {
              stateSignal$1.value = nextState;
              transitionSignal$1.value = {
                prev: prevState,
                next: nextState,
                action: action,
                created_at: DateTime.now()
              };
            });
      }
      
    });

function dispatch$3(action) {
  actionSignal$2.value = action;
}

function getToasts() {
  var state = stateSignal$1.value;
  if (typeof state !== "object") {
    return [];
  } else {
    return state._0;
  }
}

var ToasterFSM = {
  actionSignal: actionSignal$2,
  reduce: reduce$3,
  stateSignal: stateSignal$1,
  transitionSignal: transitionSignal$1,
  dispatch: dispatch$3,
  getToasts: getToasts
};

var stateSignal$2 = Signals.signal("Idle");

function reduce$4(prevState, action) {
  if (typeof action !== "object") {
    return prevState;
  }
  action.TAG === "NewTask";
  if (typeof prevState !== "object") {
    if (typeof action === "object") {
      if (action.TAG === "NewTask") {
        return {
                TAG: "NewTask",
                _0: reduce$1("Inactive", action._0)
              };
      } else {
        return {
                TAG: "Task",
                _0: reduce("Inactive", action._0)
              };
      }
    }
    
  } else if (prevState.TAG === "Task") {
    if (typeof action === "object") {
      if (action.TAG === "NewTask") {
        return {
                TAG: "NewTask",
                _0: reduce$1("Inactive", action._0)
              };
      } else {
        return {
                TAG: "Task",
                _0: reduce("Inactive", action._0)
              };
      }
    }
    
  } else if (typeof action === "object") {
    if (action.TAG === "NewTask") {
      return {
              TAG: "NewTask",
              _0: reduce$1(prevState._0, action._0)
            };
    } else {
      return {
              TAG: "Task",
              _0: reduce("Inactive", action._0)
            };
    }
  }
  
}

var transitionSignal$2 = Signals.signal({
      prev: "Idle",
      next: "Idle",
      action: "Init",
      created_at: DateTime.now()
    });

Signals.effect(function () {
      var action = actionSignal.value;
      var prevState = stateSignal$2.peek();
      var nextState = reduce$4(prevState, action);
      if (prevState !== nextState) {
        Signals.batch(function () {
              stateSignal$2.value = nextState;
              transitionSignal$2.value = {
                prev: prevState,
                next: nextState,
                action: action,
                created_at: DateTime.now()
              };
            });
      }
      
    });

var AppFSM = {
  stateSignal: stateSignal$2,
  reduce: reduce$4,
  transitionSignal: transitionSignal$2,
  dispatch: rootDispatch
};

Signals.effect(function () {
      var match = transitionSignal$2.value;
      var action = match.action;
      var tmp = match.next;
      if (typeof tmp === "object" && tmp.TAG !== "Task" && typeof action === "object" && action.TAG === "NewTask") {
        var tmp$1 = action._0;
        if (typeof tmp$1 === "object" && tmp$1.TAG === "Saved") {
          Signals.batch(function () {
                actionSignal$1.value = "Fetch";
              });
        }
        
      }
      
    });

function newTaskState_encode(v) {
  if (typeof v !== "object") {
    return ["Init"];
  } else {
    return [
            "Active",
            Task.draft_encode(v._0)
          ];
  }
}

function newTaskState_decode(v) {
  if (!Array.isArray(v) && (v === null || typeof v !== "object") && typeof v !== "number" && typeof v !== "string" && typeof v !== "boolean") {
    return Spice.error(undefined, "Not a variant", v);
  }
  if (!Array.isArray(v)) {
    return Spice.error(undefined, "Not a variant", v);
  }
  if (v.length === 0) {
    return Spice.error(undefined, "Expected variant, found empty array", v);
  }
  var match = Belt_Array.getExn(v, 0);
  if (!(!Array.isArray(match) && (match === null || typeof match !== "object") && typeof match !== "number" && typeof match !== "string" && typeof match !== "boolean") && typeof match === "string") {
    switch (match) {
      case "Active" :
          if (v.length !== 2) {
            return Spice.error(undefined, "Invalid number of arguments to variant constructor", v);
          }
          var v0 = Task.draft_decode(Belt_Array.getExn(v, 1));
          if (v0.TAG === "Ok") {
            return {
                    TAG: "Ok",
                    _0: {
                      TAG: "Active",
                      _0: v0._0
                    }
                  };
          }
          var e = v0._0;
          return {
                  TAG: "Error",
                  _0: {
                    path: "[0]" + e.path,
                    message: e.message,
                    value: e.value
                  }
                };
      case "Init" :
          if (v.length !== 1) {
            return Spice.error(undefined, "Invalid number of arguments to variant constructor", v);
          } else {
            return {
                    TAG: "Ok",
                    _0: "Init"
                  };
          }
      default:
        
    }
  }
  return Spice.error(undefined, "Invalid variant constructor", Belt_Array.getExn(v, 0));
}

function taskState_encode(v) {
  if (typeof v !== "object") {
    return ["Init"];
  } else {
    return [
            "Selected",
            Spice.stringToJson(v._0)
          ];
  }
}

function taskState_decode(v) {
  if (!Array.isArray(v) && (v === null || typeof v !== "object") && typeof v !== "number" && typeof v !== "string" && typeof v !== "boolean") {
    return Spice.error(undefined, "Not a variant", v);
  }
  if (!Array.isArray(v)) {
    return Spice.error(undefined, "Not a variant", v);
  }
  if (v.length === 0) {
    return Spice.error(undefined, "Expected variant, found empty array", v);
  }
  var match = Belt_Array.getExn(v, 0);
  if (!(!Array.isArray(match) && (match === null || typeof match !== "object") && typeof match !== "number" && typeof match !== "string" && typeof match !== "boolean") && typeof match === "string") {
    switch (match) {
      case "Init" :
          if (v.length !== 1) {
            return Spice.error(undefined, "Invalid number of arguments to variant constructor", v);
          } else {
            return {
                    TAG: "Ok",
                    _0: "Init"
                  };
          }
      case "Selected" :
          if (v.length !== 2) {
            return Spice.error(undefined, "Invalid number of arguments to variant constructor", v);
          }
          var v0 = Spice.stringFromJson(Belt_Array.getExn(v, 1));
          if (v0.TAG === "Ok") {
            return {
                    TAG: "Ok",
                    _0: {
                      TAG: "Selected",
                      _0: v0._0
                    }
                  };
          }
          var e = v0._0;
          return {
                  TAG: "Error",
                  _0: {
                    path: "[0]" + e.path,
                    message: e.message,
                    value: e.value
                  }
                };
      default:
        
    }
  }
  return Spice.error(undefined, "Invalid variant constructor", Belt_Array.getExn(v, 0));
}

function t_encode(v) {
  if (typeof v !== "object") {
    return ["Idle"];
  } else if (v.TAG === "Task") {
    return [
            "Task",
            taskState_encode(v._0)
          ];
  } else {
    return [
            "NewTask",
            newTaskState_encode(v._0)
          ];
  }
}

function t_decode(v) {
  if (!Array.isArray(v) && (v === null || typeof v !== "object") && typeof v !== "number" && typeof v !== "string" && typeof v !== "boolean") {
    return Spice.error(undefined, "Not a variant", v);
  }
  if (!Array.isArray(v)) {
    return Spice.error(undefined, "Not a variant", v);
  }
  if (v.length === 0) {
    return Spice.error(undefined, "Expected variant, found empty array", v);
  }
  var match = Belt_Array.getExn(v, 0);
  if (!(!Array.isArray(match) && (match === null || typeof match !== "object") && typeof match !== "number" && typeof match !== "string" && typeof match !== "boolean") && typeof match === "string") {
    switch (match) {
      case "Idle" :
          if (v.length !== 1) {
            return Spice.error(undefined, "Invalid number of arguments to variant constructor", v);
          } else {
            return {
                    TAG: "Ok",
                    _0: "Idle"
                  };
          }
      case "NewTask" :
          if (v.length !== 2) {
            return Spice.error(undefined, "Invalid number of arguments to variant constructor", v);
          }
          var v0 = newTaskState_decode(Belt_Array.getExn(v, 1));
          if (v0.TAG === "Ok") {
            return {
                    TAG: "Ok",
                    _0: {
                      TAG: "NewTask",
                      _0: v0._0
                    }
                  };
          }
          var e = v0._0;
          return {
                  TAG: "Error",
                  _0: {
                    path: "[0]" + e.path,
                    message: e.message,
                    value: e.value
                  }
                };
      case "Task" :
          if (v.length !== 2) {
            return Spice.error(undefined, "Invalid number of arguments to variant constructor", v);
          }
          var v0$1 = taskState_decode(Belt_Array.getExn(v, 1));
          if (v0$1.TAG === "Ok") {
            return {
                    TAG: "Ok",
                    _0: {
                      TAG: "Task",
                      _0: v0$1._0
                    }
                  };
          }
          var e$1 = v0$1._0;
          return {
                  TAG: "Error",
                  _0: {
                    path: "[0]" + e$1.path,
                    message: e$1.message,
                    value: e$1.value
                  }
                };
      default:
        
    }
  }
  return Spice.error(undefined, "Invalid variant constructor", Belt_Array.getExn(v, 0));
}

var Serialize = {
  newTaskState_encode: newTaskState_encode,
  newTaskState_decode: newTaskState_decode,
  taskState_encode: taskState_encode,
  taskState_decode: taskState_decode,
  t_encode: t_encode,
  t_decode: t_decode
};

Signals.effect(function () {
      var transition = transitionSignal$2.value;
      var state = transition.next;
      if (typeof state === "object" && state.TAG !== "Task") {
        var state$1 = state._0;
        if (typeof state$1 === "object" && state$1.TAG === "Active") {
          var data = {
            TAG: "NewTask",
            _0: {
              TAG: "Active",
              _0: state$1._0
            }
          };
          var encoded = t_encode(data);
          var json = JSON.stringify(encoded);
          console.log("json", json);
        }
        
      }
      console.log("transition", transition);
    });

export {
  Actions ,
  actionSignal ,
  rootDispatch ,
  TaskFSM ,
  NewTaskFSM ,
  TasksFSM ,
  ToasterFSM ,
  AppFSM ,
  Serialize ,
}
/* actionSignal Not a pure module */
