// Generated by ReScript, PLEASE EDIT WITH CARE

import * as CSSUtils from "./CSSUtils.res.mjs";
import * as PreactHeroicons from "preact-heroicons";
import * as JsxRuntime from "preact/jsx-runtime";

function Toast(props) {
  var toast = props.toast;
  var match = toast.status;
  var color;
  switch (match) {
    case "Success" :
        color = "bg-emerald-400";
        break;
    case "Error" :
        color = "bg-rose-400";
        break;
    case "Info" :
        color = "bg-sky-400";
        break;
    
  }
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("div", {
                      className: CSSUtils.classNames([
                            "absolute left-0 top-0 bottom-0 w-[3px]",
                            color
                          ])
                    }),
                JsxRuntime.jsx("button", {
                      children: JsxRuntime.jsx(PreactHeroicons.XIcon, {
                            className: "size-4"
                          })
                    }),
                JsxRuntime.jsx("h1", {
                      children: toast.title
                    }),
                JsxRuntime.jsx("p", {
                      children: toast.message
                    })
              ],
              className: "bg-gray-800 rounded-lg p-4 relative shadow-md"
            });
}

var make = Toast;

export {
  make ,
}
/* preact-heroicons Not a pure module */
