// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "preact/jsx-runtime";

function App(props) {
  return JsxRuntime.jsx("div", {});
}

var make = App;

export {
  make ,
}
/* preact/jsx-runtime Not a pure module */
