// Generated by ReScript, PLEASE EDIT WITH CARE


var Signal = {};

var $$AbortController = {
  Signal: Signal
};

var $$MouseEvent = {};

export {
  $$AbortController ,
  $$MouseEvent ,
}
/* No side effect */
