// Generated by ReScript, PLEASE EDIT WITH CARE

import * as App from "./App.res.mjs";
import * as Preact from "preact";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as JsxRuntime from "preact/jsx-runtime";

import './index.css'
;

var domElement = document.querySelector("#root");

if (domElement !== undefined) {
  Preact.render(JsxRuntime.jsx(App.make, {}), Caml_option.valFromOption(domElement));
}

export {
  
}
/*  Not a pure module */
