// Generated by ReScript, PLEASE EDIT WITH CARE

import * as State from "./State.res.mjs";
import * as Preact from "preact";
import * as Sidebar from "./Sidebar.res.mjs";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as JsxRuntime from "preact/jsx-runtime";

import 'vite/modulepreload-polyfill'
;

import './index.css'
;

var domElement = document.querySelector("#sidebar-root");

if (domElement !== undefined) {
  Preact.render(JsxRuntime.jsx(Sidebar.make, {}), Caml_option.valFromOption(domElement));
}

window.openSidebar = (function (button) {
    console.log(button);
  });

window.newTask = (function (_button) {
    State.AppFSM.dispatch({
          TAG: "NewTask",
          _0: "Create"
        });
  });

export {
  
}
/*  Not a pure module */
