// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "preact/jsx-runtime";

function NewTaskForm(props) {
  var onSubmit = function (e) {
    e.preventDefault();
  };
  return JsxRuntime.jsxs("form", {
              children: [
                JsxRuntime.jsx("header", {
                      children: JsxRuntime.jsx("h2", {
                            children: "New Task",
                            className: "text-xl"
                          })
                    }),
                JsxRuntime.jsxs("section", {
                      children: [
                        JsxRuntime.jsx("label", {
                              children: "Title",
                              className: "block",
                              htmlFor: "id_title"
                            }),
                        JsxRuntime.jsx("input", {
                              name: "title",
                              type: "text"
                            })
                      ]
                    })
              ],
              className: "gap-2",
              onSubmit: onSubmit
            });
}

var make = NewTaskForm;

export {
  make ,
}
/* preact/jsx-runtime Not a pure module */
