// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "preact/jsx-runtime";

function Sidebar(props) {
  return JsxRuntime.jsx("div", {
              children: "It Works",
              className: ""
            });
}

var make = Sidebar;

export {
  make ,
}
/* preact/jsx-runtime Not a pure module */
