// Generated by ReScript, PLEASE EDIT WITH CARE

import * as State from "./State.res.mjs";
import * as CSSUtils from "./CSSUtils.res.mjs";
import * as NewTaskForm from "./NewTaskForm.res.mjs";
import * as JsxRuntime from "preact/jsx-runtime";

function Sidebar(props) {
  var state = State.AppFSM.stateSignal.value;
  var isActive;
  isActive = typeof state !== "object" ? false : true;
  var tmp;
  tmp = typeof state !== "object" || state.TAG === "Task" ? null : JsxRuntime.jsx(NewTaskForm.make, {
          state: state._0
        });
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsx("div", {
                    children: tmp,
                    className: "w-[30rem] p-4"
                  }),
              className: CSSUtils.classNames([
                    "bg-gray-200 dark:bg-slate-700/20 overflow-hidden transition-all duration-500",
                    isActive ? "w-[30rem]" : "w-0"
                  ])
            });
}

var make = Sidebar;

export {
  make ,
}
/* State Not a pure module */
