// Generated by ReScript, PLEASE EDIT WITH CARE

import * as State from "./State.res.mjs";
import * as JsxRuntime from "preact/jsx-runtime";

function TasksIndex$TaskRow(props) {
  var task = props.task;
  return JsxRuntime.jsxs("tr", {
              children: [
                JsxRuntime.jsx("td", {
                      children: task.title
                    }),
                JsxRuntime.jsx("td", {
                      children: task.estimated_time.toString(),
                      className: "py-3 px-4 border-b"
                    }),
                JsxRuntime.jsx("td", {
                      children: task.tracked_time.toString(),
                      className: "py-3 px-4 border-b"
                    })
              ]
            });
}

var TaskRow = {
  make: TasksIndex$TaskRow
};

function TasksIndex$TasksTable(props) {
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsxs("table", {
                    children: [
                      JsxRuntime.jsx("thead", {
                            children: JsxRuntime.jsxs("tr", {
                                  children: [
                                    JsxRuntime.jsx("th", {
                                          children: "Name",
                                          className: "py-3 px-4 text-left"
                                        }),
                                    JsxRuntime.jsx("th", {
                                          children: "Estimated Time",
                                          className: "py-3 px-4 text-left"
                                        }),
                                    JsxRuntime.jsx("th", {
                                          children: "Tracked Time",
                                          className: "py-3 px-4 text-left"
                                        }),
                                    JsxRuntime.jsx("th", {
                                          children: "Due Date",
                                          className: "py-3 px-4 text-left"
                                        }),
                                    JsxRuntime.jsx("th", {
                                          children: "Status",
                                          className: "py-3 px-4 text-left"
                                        })
                                  ]
                                }),
                            className: "bg-gray-100 dark:bg-slate-600"
                          }),
                      JsxRuntime.jsx("tbody", {
                            children: props.tasks.map(function (task) {
                                  return JsxRuntime.jsx(TasksIndex$TaskRow, {
                                              task: task
                                            }, task.id);
                                })
                          })
                    ],
                    className: "min-w-full table-auto"
                  }),
              className: "overflow-x-auto shadow-md rounded-lg"
            });
}

var TasksTable = {
  make: TasksIndex$TasksTable
};

function TasksIndex(props) {
  var onClick = function (_e) {
    State.AppFSM.dispatch({
          TAG: "NewTask",
          _0: "Create"
        });
  };
  return JsxRuntime.jsxs("section", {
              children: [
                JsxRuntime.jsxs("header", {
                      children: [
                        JsxRuntime.jsx("h1", {
                              children: "Tasks",
                              className: "text-2xl font-bold"
                            }),
                        JsxRuntime.jsx("div", {
                              children: JsxRuntime.jsx("button", {
                                    children: "New Task",
                                    className: "btn bg-blue-500",
                                    onClick: onClick
                                  }),
                              className: "inline-flex flex-row gap-2 justify-end"
                            })
                      ],
                      className: "flex flex-row justify-between items-end"
                    }),
                JsxRuntime.jsx(TasksIndex$TasksTable, {
                      tasks: props.tasks
                    })
              ],
              className: "space-y-4",
              id: "tasks-container"
            });
}

var make = TasksIndex;

export {
  TaskRow ,
  TasksTable ,
  make ,
}
/* State Not a pure module */
